spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms_data
    username: auwal
    password: 051992
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: update
    show-sql: true
    sql:
      init:
        mode: always
        continue-on-error: true

vaadin:
  production-mode: false
  launch-browser: true

mybatis:
  mapper-locations: classpath:com/sms/mappers/*.xml
  type-aliases-package: com.sms.entities
  configuration:
    map-underscore-to-camel-case: true # Converts first_name to firstName

server:
  servlet:
    session:
      timeout: 15m

paystack:
  secret-key: sk_test_e7fd3716c1beec1ca1c788208040db93d472ec93