spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms_data
    username: auwal
    password: 051992
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

vaadin:
  production-mode: false
  launch-browser: true

mybatis:
  mapper-locations: classpath:com/sms/mappers/*.xml
  type-aliases-package: com.sms.entities
  configuration:
    map-underscore-to-camel-case: true # Converts first_name to firstName

server:
  servlet:
    session:
      timeout: 1m